### ISSUE TITLE
Queries questions/suggestions

### ISSUE THREAD

**Issue by inactive123** [ficoos/rarchdb#7]
One query I tried where I tried directly matching an entry's name:

./rarchdb_tool snes.rdb query "{'name' : '[BIOS] CX4 (World)'}"

This yielded nothing.

I then tried looking for a substring like this:

./rarchdb_tool snes.rdb query "{'name' : 'BIOS'}"

this yielded nothing too.

Note that snes.rdb is a valid rarchdb database but does not have any indexes generated yet.

Am I missing anything or is this kind of substring pattern matching simply not implemented yet?

**Comment by ficoos** [comment]
Fixed using the GLOB() predicate
